#!/usr/bin/env bash

is_x_session () {
    [[ $(xhost >& /dev/null) ]] && return 0 || return 1
}

aur () {
    # Download and upgrade given AUR package (yay AUR helper by default)
    package_name=${1:-yay}
    download_path=/tmp/${package_name}

    # Ensure the base-devel package group is instulled
    missing_dependencies=$(pacman --deptest $(pacman -Sgq base-devel))
    [[ ! -z $missing_dependencies ]] && 
        { sudo pacman --noconfirm -S $missing_dependencies; }

    # Acquire build files
    [[ -d ${download_path} ]] && sudo rm -r ${download_path}
    git clone https://aur.archlinux.org/${package_name}.git ${download_path}

    # Build the package
    echo "starting package building..."
    (cd ${download_path} && makepkg PKGBUILD)

    # Install the package
    sudo pacman -U $(find ${download_path} -name "${package_name}*.pkg*")
}

#extract() {
    #local c e i

    #(($#)) || return

    #for i; do
        #c=''
        #e=1

        #if [[ ! -r $i ]]; then
            #echo "$0: file is unreadable: \`$i'" >&2
            #continue
        #fi

        #case $i in
            #*.t@(gz|lz|xz|b@(2|z?(2))|a@(z|r?(.@(Z|bz?(2)|gz|lzma|xz)))))
                   #c=(bsdtar xvf);;
            #*.7z)  c=(7z x);;
            #*.Z)   c=(uncompress);;
            #*.bz2) c=(bunzip2);;
            #*.exe) c=(cabextract);;
            #*.gz)  c=(gunzip);;
            #*.rar) c=(unrar x);;
            #*.xz)  c=(unxz);;
            #*.zip) c=(unzip);;
            #*.zst) c=(unzstd);;
            #*)     echo "$0: unrecognized file extension: \`$i'" >&2
                   #continue;;
        #esac

        #command "${c[@]}" "$i"
        #((e = e || $?))
    #done
    #return "$e"
#}
