#!/usr/bin/env bash
# 
# Opens dmenu-chosen config file in text editor
# It does not open new window so that terminal must be provided by wm-app
# 
# i3-wm example:
#   bindcode $mod+Shift+f exec $terminal -e dmconf

EDITOR="${EDITOR:=nvim}"
declare -a options=(
"alacritty - $HOME/.config/alacritty/alacritty.yml"
"bash_aliases - $HOME/.config/.bash_aliases"
"bash_functions - $HOME/.config/.bash_functions"
"bash_profile - $HOME/.bash_profile"
"bashrc - $HOME/.bashrc"
"i3 - $HOME/.config/i3/config"
"i3blocks - $HOME/.config/i3/i3blocks.conf"
"nvim - $HOME/.config/nvim/init.vim"
"qtile - $HOME/.config/qtile/config"
"task - $HOME/.config/taskrc"
"xinit - $HOME/.config/X11/xinitrc"
"quit"
)

# Pipe options array into dmenu
# We use "printf '%s\n'" to format the array one item to ane
choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i -p 'Edit config: ')

[[ "${choice}" == "quit" ]] && echo "quit was chosen" && exit
[[ "${choice}" ]] && $EDITOR $(printf '%s\n' "${choice}" | awk '{print $NF}')
